#修改端口号
server:
  port: 8082
#定别名
mybatis:
  type-aliases-package: com.itgaoshu.bean
  #配置映射文件
  mapper-locations: classpath:mapper/*Mapper.xml

spring:
  datasource:
    #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接路径
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=Asia/Shanghai
    #用户名
    username: root
    #密码
    password: 1234
  redis:
    #redisIP地址
    host: 127.0.0.1
    #redis端口号
    port: 6379
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML



